server:
  port: 8081
spring:
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url:
    username:
    password:
notification:
  pattern: ^(?<date>((0[1-9]|[1-3]\d)\.(0[1-9]|1[0-2])\.20[2-9]\d (0\d|[1-2]\d):(0[1-9]|[1-5]\d))) (?<message>.+)$
  format:
    date: dd.MM.yyyy HH:mm